# Generated by Django 5.0.3 on 2024-03-18 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(default='Jovan', max_length=50)),
                ('last_name', models.CharField(default='Jovanovic', max_length=50)),
                ('email', models.CharField(default='jova@gmail.com', max_length=50)),
                ('phone', models.CharField(default='060-000-000', max_length=50)),
                ('address', models.CharField(default='Sunshine Boulevar no 43', max_length=50)),
                ('city', models.CharField(default='New York', max_length=50)),
                ('state', models.CharField(default='Texas', max_length=50)),
                ('zipcode', models.CharField(default='324', max_length=50)),
            ],
        ),
    ]
